version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: meet
    restart: on-failure
    ports:
    - 27017:27017

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: meet
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  min-io:
    image: minio/minio:latest
    container_name: min-io
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: mini-io-access-key
      MINIO_SECRET_KEY: minio-secret-key
    command: server /data