server:
  port: ${SERVER_PORT}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  devtools:
    add-properties: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false